### ISSUE TITLE
Samvera Adopters map not displaying

### ISSUE THREAD

**Issue by heathergreerklein** [samvera-labs/samvera.org#21]
https://samvera-labs.github.io/samvera.org/who-uses-samvera/samvera-adopters

iframe embedded link text appears; expected appearance is an embedded Google Map.

**Comment by adamjarling** [comment]
@heathergreerklein This is now working.

![image](https://user-images.githubusercontent.com/3020266/211885444-e4440f4f-551b-402a-bdb3-95f78c5da110.png)
