### ISSUE TITLE
Images missing throughout website

### ISSUE THREAD

**Issue by heathergreerklein** [samvera-labs/samvera.org#24]
Images that were embedded in the WordPress site are displaying broken image icons next to captions. 

For example, see the bottom of https://samvera-labs.github.io/samvera.org/who-uses-samvera/case-studies  

Compare to https://samvera.org/samvera-partners/case-studies/ where three screenshots are displayedat the bottom of the page.

Is it possible to migrate associated media files from the WordPress site?

**Comment by adamjarling** [comment]
@heathergreerklein Looks like the images made it over, but the paths are getting broken on the static build I'm guessing...  Looking into it.

https://github.com/samvera-labs/samvera.org/tree/main/public/images

**Comment by adamjarling** [comment]
Update, so images are pulling through in the context of the NextJS application, but the issue is relative paths in the Markdown files, like so:

![image](https://user-images.githubusercontent.com/3020266/211411515-b1d92fe9-9ec5-463e-8451-954143f1c83e.png)

I'll look into a possible batch way of fixing these in the markdown files.

**Comment by adamjarling** [comment]
@heathergreerklein So the final fix is now pushed to `/main`.  In each markdown file you'll want to do an absolute path to the image.  In NextJS, we can reference items in the `/public` folder directly, so for a dir structure like this...

```
/public
  /images
    image1.jpg
    image2.jpg
    ...
```

from a markdown file ...
```md
/markdown
  file1.md

# Like this

New Homepage
![Screenshot of Emory's new homepage](../images/emory-new-homepage-1024x491.png)
```

**Comment by heathergreerklein** [comment]
Excellent, thank you Adam! That makes sense to me.
