### ISSUE TITLE
FAQ page links not working

### ISSUE THREAD

**Issue by adamjarling** [samvera-labs/samvera.org#27]
Currently on the FAQ page (`/markdown/about/faq.md`), the in-page content links are not working, due to likely how the markdown was generated.  I put an example of how to fix this...which you can see in the first link:

![image](https://user-images.githubusercontent.com/3020266/211909802-2d9b66ee-48f0-42d4-8c61-272edbe87a66.png)

It appears the markdown parser we're using puts a "user-content" in front of the `id`s, so this link would look like:

```md
[**What is Samvera?**](#user-content-01)
```
And then the content headline:

![image](https://user-images.githubusercontent.com/3020266/211910092-20100704-ed5b-4d33-a391-af0c5e63d674.png)

Should look like this (use HTML syntax)
```html
<h3 id="01">What is Samvera?</h3>
```

@heathergreerklein Feel free to try this out and see if it makes sense?

**Comment by heathergreerklein** [comment]
Fixed by https://github.com/samvera-labs/samvera.org/pull/29 Thank you @BiljanaKotev !
