### ISSUE TITLE
Dynamically generating pages for news and events posts

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/samvera.org#5]
@adamjarling Thanks for updating the README. I want to make sure I understand this part:

> Within each child directory (ie. `pages/about`), is a file called `[slug].jsx`. This is a React component wired up to display dynamic content pulled in from the Markdown files mentioned above. In each `[slug].jsx` file, you'll make it unique by updating a `CONFIG` variable defined in the component. For example in the "About" folder:

```
const CONFIG = {
  parentDir: "about",
  parentDirLabel: "About Samvera",
};
```

The markdown files for "News & Events" blog posts are organized in a directory called `posts` with subdirectories for years (e.g. `2022`) and months (e.g. `04`). Does this look like the to-do list:

- [ ] Create a new folders in `markdown` for posts in subdirectories organized by year and month (e.g. `markdown/2022/04`) and place all of the posts for that section of the site within that directory accordingly
- [ ] Mirror that directory structure in `pages` (e.g. `pages/2022/04`) and place a `[slug].jsx`  at the root of each subdirectory that contains a corresponding markdown file
- [ ] Update the `CONFIG` variable in each `[slug].jsx` file that includes the parent directory of the file and the breadcrumb label for the rendered page

For example,

- This blog post page: https://samvera.org/2014/01/06/new-releases-for-the-new-year/
- Will be rendered using a markdown file: `markdown/2014/01/06/new-releases-for-the-new-year.md`
- And a React component: `pages/2014/01/06/[slug].jsx`
- Containing the following variable:

```
const CONFIG = {
  parentDir: "2014/01/06",
  parentDirLabel: "News & Events",
};
```

Does that sound right to you? That seems simple, but I'm wondering how to handle migrating the "News & Events" posts without a lot of manual work.

**Comment by adamjarling** [comment]
@chrisdaaz Yea, _in theory_ this should hold as a pattern for how to move the old site, markdown content into Next's page building system.   I'll give this a quick test run today and see if it works for deep nested directory structure like the `posts`, or if there are any gotchas I can smooth out so you can port the content over.
